### ISSUE TITLE
feat: Initail View and App/SceneDelegate

### ISSUE THREAD

**Issue by GREENOVER** [depromeet/mongsil-iOS#2]
### Task
- App/SceneDelegate 생성, 설정 및 초기 앱 뷰/코어 틀 구성
- 폴더 및 파일 그룹화

### List
- [x] AppDelegate 파일 생성 및 기본 틀 로직 구현
- [x] SceneDelegate 파일 생성 및 기본 틀 로직 구현
- [x] AppView / AppCore 기본 로직 구현
- [x] 폴더 및 파일 초기 그룹화 작업
