### ISSUE TITLE
feat: Helpful extension code

### ISSUE THREAD

**Issue by GREENOVER** [depromeet/mongsil-iOS#3]
### Task
- 아키텍쳐 사용 및 기능 구현에 도움이 되는 확장 코드파일 추가

### List
- [x] ForEachIndex 코드 추가
- [x] SharedState 코드 추가
- [x] Effect Extension 코드 추가
- [x] Reducer Extension 코드 추가
- [x] Combine Extension 코드 추가
