### ISSUE TITLE
feat: Add Home Initial View

### ISSUE THREAD

**Issue by GREENOVER** [depromeet/mongsil-iOS#47]
### Task
- 홈 첫 화면 뷰 구현
- 디자인 시스템 반영

### List
- [x] 홈 첫 화면 뷰/코어 구현
- [x] 폰트 디자인 시스템 변경 부분 반영
- [x] 컬러 디자인 시스템 변경 부분 반영
- [x] 아이콘 디자인 시스템 변경 부분 반영
- [x] 토스트 메시지 디자인 시스템 변경 부분 반영
