### ISSUE TITLE
feat: Add Storage View and Core

### ISSUE THREAD

**Issue by GREENOVER** [depromeet/mongsil-iOS#52]
### Task
- [x] 월 별 선택 바텀 시트 구현
- [x] 꿈일기 / 해몽 삭제 기능 구현
- [x] 유저 해몽 정보에 대한 post API 연동 구현
- [x] 유저 해몽 삭제에 대한 delete API 연동 구현
- [x] 얼럿 디자인 수정건 반영
- [x] 네비게이션 바 디자인 수정건 최종 반영
